<!doctype html>
<html lang=en >
<head>
<title>opendesk-slim-chair-app R1.2</title>
<meta charset=utf-8 />
<meta name=viewport content='width=device-width,user-scalable=no,minimum-scale=1.0,maximum-scale=1.0' />
</head>
<body>
<script src=http://mrdoob.github.io/three.js/build/three.min.js ></script>
<script src=http://mrdoob.github.io/three.js/examples/js/controls/OrbitControls.js ></script>
<script src=http://mrdoob.github.io/three.js/examples/js/libs/stats.min.js ></script>
<script>
	var pi = Math.PI, pi05 = pi * 0.5, pi2 = pi + pi;
	var d2r = pi / 180, r2d = 180 / pi;  // degrees / radians

	var thickness;
	var widthChair;
	var depthSeat;
	var heightSeat;
	var depthSupport = 350;

	var angleLegs = ( 360 - 77 ) * d2r;

	var slimChair;

	var css, menu, stats, renderer, scene, camera, controls;
	var geometry, material, mesh;

	init();
	animate();

	function init() {

		css = document.head.appendChild( document.createElement( 'style' ) );
		css.innerHTML ='body { font: 600 12pt monospace; margin: 0; overflow: hidden; }' +

			'#i {text-decoration: none; }' +
		'';

		menu = document.body.appendChild( document.createElement( 'div' ) );
		menu.style.cssText = 'margin: 0 20px; max-width: 250px; position: absolute; z-index: 1; ';
		menu.innerHTML = '<h2 style=margin:0; ><a href="" >' + document.title + '</a> ' +
			'<a id=i href=http://opendesk.github.io/design-playground/ >&#x24D8;</a></h2>' +
			'<p>first steps in building an app for the Slim Chair by Jose Pacheco</p>' +
			'<p><a href="opendesk-slim-chair-lorenz-attractor-r1.html" >Bring the Action</a></p>' +
			'<p><input type=range id=inpThickness min=1 max=50 step=1 value=18 ontouchmove=drawChair(); onmousemove=drawChair(); /> Thickness</p>' +
			'<p><input type=range id=inpWidth min=220 max=700 step=10 value=410 ontouchmove=drawChair(); onmousemove=drawChair(); /> Width</p>' +
			'<p><input type=range id=inpHeightSeat min=200 max=800 step=10 value=410 ontouchmove=drawChair(); onmousemove=drawChair(); /> Seat Height</p>' +
			'<p><input type=range id=inpDepthSeat min=200 max=500 step=10 value=380 ontouchmove=drawChair(); onmousemove=drawChair(); /> Seat Depth</p>' +
			'<div id=info ></div>' +
		'';



		stats = new Stats();
		stats.domElement.style.cssText = 'position: absolute; right: 0; top: 0; z-index: 100; ';
		document.body.appendChild( stats.domElement );

		renderer = new THREE.WebGLRenderer( { alpha: 1, antialias: true, clearColor: 0xffffff }  );
		renderer.setSize( window.innerWidth, window.innerHeight );
		document.body.appendChild( renderer.domElement );

		camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 5000 );
		camera.position.set( 1000, 1000, 1000 );

		controls = new THREE.OrbitControls( camera, renderer.domElement );
		controls.maxDistance = 5000;
		controls.target.set( 0, 200, 0 );

		scene = new THREE.Scene();

		window.addEventListener( 'resize', onWindowResize, false );

// ground
		geometry = new THREE.BoxGeometry( 1000, 20, 1000 );
		material = new THREE.MeshNormalMaterial( { opacity: 0.5, transparent: true } );
		mesh = new THREE.Mesh( geometry, material );
		mesh.position.set( 250, -20, 250 );
		scene.add( mesh );

		mesh = new THREE.GridHelper( 500, 50 );
		mesh.position.set( 250, -9, 250 );
		scene.add( mesh );

		var axisHelper = new THREE.AxisHelper( 500 );
		scene.add( axisHelper );


		drawChair();

	}


	function drawChair() {

		thickness = parseFloat( inpThickness.value );
		widthChair = parseFloat( inpWidth.value );
		heightSeat = parseFloat( inpHeightSeat.value );
		depthSeat = parseFloat( inpDepthSeat.value );

		scene.remove( slimChair );

		slimChair = new THREE.Object3D()

		material = new THREE.MeshNormalMaterial( { opacity: 0.95, transparent: true } );

		seat = drawSeat();
		seat.position.set( thickness, heightSeat, 75 );
		slimChair.add( seat );

		frontLegs = drawLeg();
		frontLegs.rotation.y = pi;
		frontLegs.position.set( widthChair, heightSeat - 5, depthSeat + 30 );
		slimChair.add( frontLegs );

		backLegs = drawLeg();
		backLegs.position.set( 0, heightSeat - 5, 100 );
		slimChair.add( backLegs );

		back = drawBack();
		back.position.set( 0, heightSeat - thickness, 105 );
		slimChair.add( back );

		supportLeft = drawSupport();
		supportLeft.position.set( 100, heightSeat - thickness, 125 )
		slimChair.add( supportLeft );

		supportRight = drawSupport();
		supportRight.position.set( widthChair - 100, heightSeat - thickness, 125 )
		slimChair.add( supportRight );


		bracketLeft = drawBracket();
		bracketLeft.position.set( thickness, heightSeat, 100 );
		slimChair.add( bracketLeft );

		bracketRight = drawBracket();
		bracketRight.position.set( widthChair,  heightSeat, 100 );
		slimChair.add( bracketRight );

		scene.add( slimChair );
	}


	function drawBracket() {

		var b = {};

		notchBracket = 180;

		depthBracket = depthSeat - 70;

		angleUpper = 74 * d2r;
		angleBack = 257 * d2r;
		angleFront = 283 * d2r;

		radiusBracketFront = 20
		radiusBracketIn = 80;
		radiusBracketTop = 40;
		radiusBracketBack = 150;

		var shape = new THREE.Shape();

//		shape.moveTo( 0, 0 );

		centerX = - radiusBracketBack  ;
		centerY = 0;
		shape.absarc( centerX, centerY, radiusBracketBack, ( 360 + 16 ) * d2r, ( 360 - 13 ) * d2r, true );


		b.p1x = ( notchBracket + thickness ) * cos( angleBack );
		b.p1y = ( notchBracket + thickness ) * sin( angleBack );
		shape.lineTo( b.p1x, b.p1y );

		b.p2x = thickness * cos( angleBack + pi05 );
		b.p2y = thickness * sin( angleBack + pi05);
		shape.lineTo( b.p1x + b.p2x, b.p1y + b.p2y );

		b.p3x = ( notchBracket - radiusBracketIn ) * cos( angleBack + pi);
		b.p3y = ( notchBracket - radiusBracketIn + 50 ) * sin( angleBack + pi);
//		shape.lineTo( b.p1x + b.p2x + b.p3x, b.p1y + b.p2y + b.p3y );

		centerX =  b.p1x + b.p2x + b.p3x + radiusBracketIn;
		centerY = b.p1y + b.p2y + b.p3y - radiusBracketIn;
		shape.absarc( centerX, centerY, radiusBracketIn, angleBack - pi05, 90 * d2r, true );

// Now starting from the other end
		b.p6x = depthBracket + ( notchBracket + thickness ) * cos( angleFront );
		b.p6y = ( notchBracket + thickness ) * sin( angleFront );

		b.p5x = thickness * cos( angleFront - pi05 );
		b.p5y = thickness * sin( angleFront - pi05);

		b.p4x = ( notchBracket - radiusBracketIn ) * cos( angleFront + pi);
		b.p4y = ( notchBracket - radiusBracketIn + 50 ) * sin( angleFront + pi);
//		shape.lineTo( b.p6x + b.p5x + b.p4x, b.p6y + b.p5y + b.p4y );

		centerX =  b.p6x + b.p5x + b.p4x - radiusBracketIn;
		centerY = b.p6y + b.p5y + b.p4y - radiusBracketIn;
		shape.absarc( centerX, centerY, radiusBracketIn, 90 * d2r, 13 * d2r, true );

		shape.lineTo( b.p6x + b.p5x, b.p6y + b.p5y );

		shape.lineTo( b.p6x, b.p6y );

// now the top
//		shape.lineTo( depthBracket, 0 );
		centerX = depthBracket - radiusBracketFront;
		centerY = - radiusBracketFront;
		shape.absarc( centerX, centerY, radiusBracketFront, 16 * d2r, pi05, true );

/*
		shape.lineTo( - notchBracket * cos( angleUpper ) - thickness * cos( angleUpper + pi05 ) - notchBracket * cos( angleUpper + pi ), 
			notchBracket * sin( angleUpper ) + thickness * sin( angleUpper + pi05) + notchBracket * sin( angleUpper + pi ) 
				- thickness * cos( angleUpper )
			);
*/

//		shape.lineTo( -20, 0 );

		centerX = radiusBracketTop + thickness;
		centerY = radiusBracketTop;
		shape.absarc( centerX, centerY, radiusBracketTop, 270 * d2r, ( 180 + 16 ) * d2r, true );


		shape.lineTo( thickness - notchBracket * cos( angleUpper ), notchBracket * sin( angleUpper ) );

		shape.lineTo( thickness - notchBracket * cos( angleUpper ) - thickness * cos( angleUpper - pi05 ) , 
			notchBracket * sin( angleUpper ) + thickness * sin( angleUpper - pi05) );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationY( -pi05 ) );

		var mesh = new THREE.Mesh( geometry, material );
//		mesh.position.set( 100, 200, 125 )

		return mesh;

	}

	function drawLeg() {

		notchLeg = 150;
		radiusLeg = 50;

		widthFoot = 0.5 * ( 410 - 334 ); 
		angleFoot = 4;

		gap = 70; // 363;
		deltaXLeg = gap * cos( ( 90 - angleFoot ) * d2r ) 

		var shape = new THREE.Shape();

		shape.moveTo( 0, 0 );
		shape.lineTo( 0, heightSeat - thickness - notchLeg );
		shape.lineTo( thickness, heightSeat - thickness - notchLeg );
		shape.lineTo( thickness, heightSeat - thickness );
//check = ( widthChair - thickness <= 5 ) ? 5 : ;
		shape.lineTo( widthChair - thickness, heightSeat - thickness );
		shape.lineTo( widthChair - thickness, heightSeat - thickness - notchLeg );
		shape.lineTo( widthChair, heightSeat - thickness - notchLeg );
		shape.lineTo( widthChair, 0 );
		shape.lineTo( widthChair - widthFoot - thickness, 0 );

		centerX = widthChair - widthFoot - deltaXLeg - radiusLeg - thickness;
		centerY = heightSeat - gap * sin( ( 90 - angleFoot ) * d2r ) - radiusLeg;
		shape.absarc( centerX, centerY, radiusLeg, angleFoot * d2r, 90 * d2r, true );
//		shape.lineTo( widthChair - widthFoot - 50, gap );

		centerX = widthFoot + deltaXLeg + radiusLeg + thickness;
		centerY = heightSeat - gap * sin( ( 90 - angleFoot ) * d2r ) - radiusLeg;
		shape.absarc( centerX, centerY, radiusLeg, 90 * d2r, ( 180 - angleFoot ) * d2r, true );
//		shape.lineTo( widthFoot + 50, gap );

		shape.lineTo( widthFoot + thickness, 0 );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeTranslation( 0, - heightSeat, 0 ) );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationX( 13 * d2r ) );

		var mesh = new THREE.Mesh( geometry, material );

		return mesh;

	}

	function drawSupport() {

		radiusSupportOut = 20
		radiusSupportIn = 20;

		depthSupport = depthSeat - 120;
		heightSupport = 70;
		heightTab = 50;

		tabDepthSupport = 30;

		deltaX = ( heightTab - radiusSupportOut - radiusSupportIn ) * cos( angleLegs ) ;
		deltaY = - heightTab * sin( angleLegs );

		var shape = new THREE.Shape();

//		shape.moveTo( 0, 0 );
		shape.moveTo( depthSupport, 0 );
		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ), heightSupport * sin( angleLegs ) );
 
		centerX = depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport + radiusSupportOut;
		centerY = heightSupport * sin( angleLegs ) + radiusSupportOut;
		shape.absarc( centerX, centerY, radiusSupportOut, 270 * d2r, angleLegs - pi05, true );
//		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport, heightSupport * sin( angleLegs ) );


		centerX = depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport - deltaX - radiusSupportIn;
		centerY = heightSupport * sin( angleLegs ) + deltaY - radiusSupportIn;
		shape.absarc( centerX, centerY, radiusSupportIn, angleLegs + pi05, 450 * d2r, true );
//		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport - deltaX, heightSupport * sin( angleLegs ) + 50 );

		centerX = heightSupport * - cos( angleLegs ) + tabDepthSupport + deltaX + radiusSupportIn;
		centerY = heightSupport * sin( angleLegs ) + deltaY - radiusSupportIn;
		shape.absarc( centerX, centerY, radiusSupportIn, 90 * d2r, ( 180 - 13 ) * d2r, true );
//		shape.lineTo( heightSupport * - cos( angleLegs ) + tabDepthSupport + deltaX, heightSupport * sin( angleLegs ) + 50 );


		centerX = heightSupport * - cos( angleLegs ) + tabDepthSupport - radiusSupportOut;
		centerY = heightSupport * sin( angleLegs ) + radiusSupportOut;
		shape.absarc( centerX, centerY, radiusSupportOut, ( 360 - 13 ) * d2r, ( 270 ) * d2r, true );
//		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport, heightSupport * sin( angleLegs ) );

//		shape.lineTo( heightSupport * - cos( angleLegs ) + tabDepthSupport, heightSupport * sin( angleLegs ) );
		shape.lineTo( heightSupport * - cos( angleLegs ), heightSupport * sin( angleLegs ) );
		shape.lineTo( 0, 0 );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationY( -pi05 ) );

		var mesh = new THREE.Mesh( geometry, material );

		return mesh;

	}


	function drawSeat() {

		notchSeat = 50;
		radiusSeat = 30;
		widthSeat = widthChair - 2 * thickness;

		var shape = new THREE.Shape();

		shape.moveTo( 0, notchSeat );
		shape.lineTo( thickness, notchSeat );
		shape.absarc( thickness + radiusSeat, notchSeat - radiusSeat, radiusSeat, 180 * d2r, 270 * d2r, true );
		shape.absarc( widthSeat - thickness - radiusSeat, radiusSeat, radiusSeat, 270 * d2r, 360 * d2r, true);
		shape.lineTo( widthSeat - thickness, notchSeat );
		shape.lineTo( widthSeat, notchSeat );
		shape.absarc( widthSeat - radiusSeat, depthSeat - radiusSeat, radiusSeat, 0 * d2r, 90 * d2r, true );
		shape.absarc( radiusSeat, depthSeat - radiusSeat, radiusSeat, 90 * d2r, 180 * d2r, true );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationX( pi05 ) );

		seat = new THREE.Mesh( geometry, material );

		return seat;

	}

	function drawBack() {

		var radiusOut = 35;
		var radiusIn = 20;
		var notchBack = 150

		heightBack = 400; //

		rail = 0.5 * ( 410 - 334 ); 
		gapTop = 90;
		gapBot = heightBack - 2 * rail - 90 

		var shape = new THREE.Shape();

		shape.moveTo( thickness, 0 );
		shape.lineTo( thickness, notchBack );
		shape.lineTo( 0, notchBack );
		shape.absarc( radiusOut, heightBack - radiusOut, radiusOut, 180 * d2r, 90 * d2r, true );
		shape.absarc( widthChair - radiusOut, heightBack - radiusOut, radiusOut, 90 * d2r, 0 * d2r, true );
		shape.lineTo( widthChair, notchBack );

		shape.lineTo( widthChair - thickness, notchBack );
		shape.lineTo( widthChair - thickness, 0 );
		shape.lineTo( widthChair - rail - thickness, 0 );
		shape.absarc( widthChair - rail - thickness - radiusIn, gapBot - radiusIn, radiusIn, 0 * d2r, 90 * d2r, true );
		shape.absarc( rail + thickness + radiusIn, gapBot - radiusIn, radiusIn, 90 * d2r, 180 * d2r, true );
		shape.lineTo( rail + thickness, 0 );

		var holePath = new THREE.Path();
		holePath.moveTo( rail + radiusIn, heightBack - rail  );
		holePath.absarc( rail + radiusIn + thickness, heightBack - rail - radiusIn, radiusIn, 90 * d2r, 180 * d2r, true );
		holePath.absarc( rail + radiusIn + thickness, heightBack - rail - gapTop + radiusIn, radiusIn, 180 * d2r, 270 * d2r, true );
		holePath.absarc( widthChair - rail - radiusIn - thickness, heightBack - rail - gapTop + radiusIn, radiusIn, 270 * d2r, 360 * d2r, true );
		holePath.absarc( widthChair - rail - radiusIn - thickness, heightBack - rail - radiusIn, radiusIn, 0 * d2r, 90 * d2r, true );
		shape.holes.push( holePath );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationX( -16 * d2r ) );

		var mesh = new THREE.Mesh( geometry, material );

		return mesh;
	}

	function cos(a){return Math.cos(a);}
	function sin(a){return Math.sin(a);}

	function onWindowResize() {

		camera.aspect = window.innerWidth / window.innerHeight;
		camera.updateProjectionMatrix();

		renderer.setSize( window.innerWidth, window.innerHeight );

	}

	function animate() {

		requestAnimationFrame( animate );
		controls.update();
		stats.update();
		renderer.render( scene, camera );

	}

</script>
</body>
</html>