<!doctype html>
<html lang=en >
<head>
<title>opendesk-slim-chair-app R1</title>
<meta charset=utf-8 />
<meta name=viewport content='width=device-width,user-scalable=no,minimum-scale=1.0,maximum-scale=1.0' />
</head>
<body>
<script src=http://mrdoob.github.io/three.js/build/three.min.js ></script>
<script src=http://mrdoob.github.io/three.js/examples/js/controls/OrbitControls.js ></script>
<script src=http://mrdoob.github.io/three.js/examples/js/libs/stats.min.js ></script>
<script>
	var pi = Math.PI, pi05 = pi * 0.5, pi2 = pi + pi;
	var d2r = pi / 180, r2d = 180 / pi;  // degrees / radians

	var thickness = 20;
	var widthChair = 410;
	var heightSeat = 450;
	var depthSupport = 350;

	var angleLegs = ( 360 - 77 ) * d2r;

	var scale = 1;



	var css, menu, stats, renderer, scene, camera, controls;
	var geometry, material, mesh;

	init();
	animate();

	function init() {

		css = document.head.appendChild( document.createElement( 'style' ) );
		css.innerHTML ='body { font: 600 12pt monospace; margin: 0; overflow: hidden; }' +

			'#i {text-decoration: none; }' +
		'';

		menu = document.body.appendChild( document.createElement( 'div' ) );
		menu.style.cssText = 'margin: 0 20px; position: absolute; ';
		menu.innerHTML = '<h2 style=margin:0; ><a href="" >' + document.title + '</a> ' +
			'<a id=i href=http://opendesk.github.io/design-playground/ >&#x24D8;</a></h2>' +
			'<p>first steps in building an app for the Slim Chair by Jose Pacheco</p>' +
			'<p><a href="opendesk-slim-chair-lorenz-attractor-r1.html" >Bring the Action</a></p>' +
			'<div id=info ></div>' +
		'';

		stats = new Stats();
		stats.domElement.style.cssText = 'position: absolute; right: 0; top: 0; z-index: 100; ';
		document.body.appendChild( stats.domElement );

		renderer = new THREE.WebGLRenderer( { alpha: 1, antialias: true, clearColor: 0xffffff }  );
		renderer.setSize( window.innerWidth, window.innerHeight );
		document.body.appendChild( renderer.domElement );

		camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 5000 );
		camera.position.set( 1000, 1000, 1000 );

		controls = new THREE.OrbitControls( camera, renderer.domElement );
		controls.maxDistance = 5000;

		scene = new THREE.Scene();

		window.addEventListener( 'resize', onWindowResize, false );

// ground
		geometry = new THREE.BoxGeometry( 1000, 20, 1000 );
		material = new THREE.MeshNormalMaterial( { opacity: 0.5, transparent: true } );
		mesh = new THREE.Mesh( geometry, material );
		mesh.position.set( 250, -20, 250 );
		scene.add( mesh );

		mesh = new THREE.GridHelper( 500, 50 );
		mesh.position.set( 250, -9, 250 );
		scene.add( mesh );

		var axisHelper = new THREE.AxisHelper( 500 );
		scene.add( axisHelper );

// assets
		var slimChair = new THREE.Object3D()

		material = new THREE.MeshNormalMaterial( { opacity: 0.95, transparent: true } );

		setat = drawSeat();
		seat.position.set( thickness, heightSeat, 75 );
		slimChair.add( seat );

		frontLegs = drawLeg();
		frontLegs.rotation.y = pi;
		frontLegs.position.set( 410, 0, 500 );
		slimChair.add( frontLegs );

		backLegs = drawLeg();
		backLegs.position.set( 0, 0, 0 );
		slimChair.add( backLegs );

		back = drawBack();
		back.position.set( 0, origin - thickness, 105 );
		slimChair.add( back );

		supportLeft = drawSupport();
		slimChair.add( supportLeft );

		supportRight = drawSupport();
		supportRight.position.x = 300;
//		slimChair.add( supportRight );


		bracketLeft = drawBracket();
		bracketLeft.position.set( 100, 600, 0 );
		slimChair.add( bracketLeft );

		bracketRight = drawBracket();
		bracketRight.position.set( 410 - thickness, 450, 100 );
//		slimChair.add( bracketRight );

		scene.add( slimChair );

	}

	function drawBracket() {

		radiusBracketFrontIn = 20
		radiusBracketIn = 80;
		radiusBracketTop = 40;
		radiusBracketBack = 150;

		notchBracket = 150;

		depthBracket = -300;

		angleBack = 257 * d2r;
		angleFront = 283 * d2r;
		angleUpper = 74 * d2r;

		var shape = new THREE.Shape();

		shape.moveTo( depthBracket, 0 );
//		shape.lineTo( depthBracket, 0 );
		shape.lineTo( depthBracket + notchBracket * cos( angleBack ), notchBracket * sin( angleBack ) );
//		shape.lineTo( notchBracket * cos( angleBack ) + 50, notchBracket * sin( angleBack ) );
		shape.lineTo( depthBracket + notchBracket * cos( angleBack ) + thickness * cos( angleBack + pi05 ), notchBracket * sin( angleBack ) + thickness * sin( angleBack + pi05) );
		shape.lineTo( depthBracket + notchBracket * cos( angleBack ) + thickness * cos( angleBack + pi05 ) + ( notchBracket -50  )* cos( angleBack + pi), 
			notchBracket * sin( angleBack ) + thickness * sin( angleBack + pi05) + ( notchBracket -50  )* sin( angleBack + pi));


		shape.lineTo( notchBracket * cos( angleFront ) + thickness * cos( angleFront - pi05 ) + ( notchBracket -50  )* cos( angleFront + pi), 
			notchBracket * sin( angleFront ) + thickness * sin( angleFront - pi05) + ( notchBracket -50  )* sin( angleFront + pi));
		shape.lineTo( notchBracket * cos( angleFront ) + thickness * cos( angleFront - pi05 ), 
			notchBracket * sin( angleFront ) + thickness * sin( angleFront - pi05) );

		shape.lineTo( notchBracket * cos( angleFront ), 
			notchBracket * sin( angleFront ) );

		shape.lineTo( 0, 0 );
		shape.lineTo( notchBracket * cos( angleUpper ), notchBracket * sin( angleUpper ) );

		shape.lineTo( notchBracket * cos( angleUpper ) + thickness * cos( angleUpper + pi05 ) , 
			notchBracket * sin( angleUpper ) + thickness * sin( angleUpper + pi05) );

		shape.lineTo( notchBracket * cos( angleUpper ) + thickness * cos( angleUpper + pi05 ) + notchBracket * cos( angleUpper + pi ), 
			notchBracket * sin( angleUpper ) + thickness * sin( angleUpper + pi05) + notchBracket * sin( angleUpper + pi ) );



		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
//		geometry.applyMatrix( new THREE.Matrix4().makeRotationY( pi05 ) );

		var mesh = new THREE.Mesh( geometry, material );
//		mesh.position.set( 100, 200, 125 )

		return mesh;

	}

	function drawLeg() {

		notchLeg = 150;
		radiusLeg = 50;

		widthFoot = 0.5 * ( 410 - 334 ); 
		angleFoot = 4;

		gap = 363;
		deltaXLeg = gap * cos( ( 90 - angleFoot ) * d2r ) 

		var shape = new THREE.Shape();

		shape.moveTo( 0, 0 );
		shape.lineTo( 0, heightSeat - notchLeg );
		shape.lineTo( thickness, heightSeat - notchLeg );
		shape.lineTo( thickness, heightSeat );
		shape.lineTo( widthChair - thickness, heightSeat );
		shape.lineTo( widthChair - thickness, heightSeat - notchLeg );
		shape.lineTo( widthChair, heightSeat - notchLeg );
		shape.lineTo( widthChair, 0 );
		shape.lineTo( widthChair - widthFoot, 0 );

		centerX = widthChair - widthFoot - deltaXLeg - radiusLeg;
		centerY = heightSeat - gap * sin( angleFoot * d2r ) - radiusLeg;
		shape.absarc( centerX, centerY, radiusLeg, angleFoot * d2r, 90 * d2r, true );
//		shape.lineTo( widthChair - widthFoot - 50, gap );

		centerX = widthFoot + deltaXLeg + radiusLeg;
		centerY = heightSeat - gap * sin( angleFoot * d2r ) - radiusLeg;
		shape.absarc( centerX, centerY, radiusLeg, 90 * d2r, ( 180 - angleFoot ) * d2r, true );
//		shape.lineTo( widthFoot + 50, gap );

		shape.lineTo( widthFoot, 0 );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationX( 13 * d2r ) );

		var mesh = new THREE.Mesh( geometry, material );

		return mesh;

	}

	function drawSupport() {

		radiusSupportOut = 20
		radiusSupportIn = 50;

		depthSupport = 250;
		heightSupport = 120;

		tabDepthSupport = 60;
		deltaX = ( 80 - 70 ) * cos( angleLegs ) ;
		deltaY = -80 * sin( angleLegs );

		var shape = new THREE.Shape();

//		shape.moveTo( 0, 0 );
		shape.moveTo( depthSupport, 0 );
		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ), heightSupport * sin( angleLegs ) );
 
		centerX = depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport + radiusSupportOut;
		centerY = heightSupport * sin( angleLegs ) + radiusSupportOut;
		shape.absarc( centerX, centerY, radiusSupportOut, 270 * d2r, angleLegs - pi05, true );
//		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport, heightSupport * sin( angleLegs ) );

		centerX = depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport - deltaX - radiusSupportIn;
		centerY = heightSupport * sin( angleLegs ) + deltaY - radiusSupportIn;
		shape.absarc( centerX, centerY, radiusSupportIn, angleLegs + pi05, 450 * d2r, true );
//		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport - deltaX, heightSupport * sin( angleLegs ) + 50 );

		centerX = heightSupport * - cos( angleLegs ) + tabDepthSupport + deltaX + radiusSupportIn;
		centerY = heightSupport * sin( angleLegs ) + deltaY - radiusSupportIn;
		shape.absarc( centerX, centerY, radiusSupportIn, 90 * d2r, ( 180 - 13 ) * d2r, true );
//		shape.lineTo( heightSupport * - cos( angleLegs ) + tabDepthSupport + deltaX, heightSupport * sin( angleLegs ) + 50 );

		centerX = heightSupport * - cos( angleLegs ) + tabDepthSupport - radiusSupportOut;
		centerY = heightSupport * sin( angleLegs ) + radiusSupportOut;
		shape.absarc( centerX, centerY, radiusSupportOut, ( 360 - 13 ) * d2r, ( 270 ) * d2r, true );
//		shape.lineTo( depthSupport + heightSupport * cos( angleLegs ) - tabDepthSupport, heightSupport * sin( angleLegs ) );

//		shape.lineTo( heightSupport * - cos( angleLegs ) + tabDepthSupport, heightSupport * sin( angleLegs ) );
		shape.lineTo( heightSupport * - cos( angleLegs ), heightSupport * sin( angleLegs ) );
		shape.lineTo( 0, 0 );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
//		geometry.applyMatrix( new THREE.Matrix4().makeRotationY( -pi05 ) );

		var mesh = new THREE.Mesh( geometry, material );
		mesh.position.set( 100, heightSeat - thickness - 200, 125 )

		return mesh;

	}


	function drawSeat() {

		notchSeat = 50;
		radiusSeat = 30;
		widthSeat = widthChair - 2 * thickness;
		depthSeat = 380;

		var material = new THREE.MeshNormalMaterial( { opacity: 0.85, transparent: true } );

		var shape = new THREE.Shape();

		shape.moveTo( 0, notchSeat );
		shape.lineTo( thickness, notchSeat );
		shape.absarc( thickness + radiusSeat, notchSeat - radiusSeat, radiusSeat, 180 * d2r, 270 * d2r, true );
		shape.absarc( widthSeat - thickness - radiusSeat, radiusSeat, radiusSeat, 270 * d2r, 360 * d2r, true);
		shape.lineTo( widthSeat - thickness, notchSeat );
		shape.lineTo( widthSeat, notchSeat );
		shape.absarc( widthSeat - radiusSeat, depthSeat - radiusSeat, radiusSeat, 0 * d2r, 90 * d2r, true );
		shape.absarc( radiusSeat, depthSeat - radiusSeat, radiusSeat, 90 * d2r, 180 * d2r, true );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationX( pi05 ) );

		seat = new THREE.Mesh( geometry, material );

		return seat;

	}



	function drawBack() {

		radiusOut = 35;
		radiusIn = 20;
		notch = 150

		height = 400; //
		origin = 450

		rail = 0.5 * ( 410 - 334 ); 
		gapTop = 90;
		gapBot = height - 2 * rail - 90 

		var material = new THREE.MeshNormalMaterial( { opacity: 0.85, transparent: true } );

		var shape = new THREE.Shape();

		shape.moveTo( thickness, 0 );
		shape.lineTo( thickness, notch );
		shape.lineTo( 0, notch );
		shape.absarc( radiusOut, height - radiusOut, radiusOut, 180 * d2r, 90 * d2r, true );
		shape.absarc( widthChair - radiusOut, height - radiusOut, radiusOut, 90 * d2r, 0 * d2r, true );
		shape.lineTo( widthChair, notch );
		shape.lineTo( widthChair - thickness, notch );
		shape.lineTo( widthChair - thickness, 0 );
		shape.lineTo( widthChair - rail, 0 );
		shape.absarc( widthChair - rail - radiusIn, gapBot - radiusIn, radiusIn, 0 * d2r, 90 * d2r, true );
		shape.absarc( rail + radiusIn, gapBot - radiusIn, radiusIn, 90 * d2r, 180 * d2r, true );
		shape.lineTo( rail, 0 );

		var holePath = new THREE.Path();
		holePath.moveTo( rail + radiusIn, height - rail  );
		holePath.absarc( rail + radiusIn, height - rail - radiusIn, radiusIn, 90 * d2r, 180 * d2r, true );
		holePath.absarc( rail + radiusIn, height - rail - gapTop + radiusIn, radiusIn, 180 * d2r, 270 * d2r, true );
		holePath.absarc( widthChair - rail - radiusIn, height - rail - gapTop + radiusIn, radiusIn, 270 * d2r, 360 * d2r, true );
		holePath.absarc( widthChair - rail - radiusIn, height - rail - radiusIn, radiusIn, 0 * d2r, 90 * d2r, true );
		shape.holes.push( holePath );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
		geometry.applyMatrix( new THREE.Matrix4().makeRotationX( -16 * d2r ) );

		var mesh = new THREE.Mesh( geometry, material );

		return mesh;
	}







	function cos(a){return Math.cos(a);}
	function sin(a){return Math.sin(a);}


	function onWindowResize() {

		camera.aspect = window.innerWidth / window.innerHeight;
		camera.updateProjectionMatrix();

		renderer.setSize( window.innerWidth, window.innerHeight );

	}

	function animate() {

		requestAnimationFrame( animate );
		controls.update();
		stats.update();
		renderer.render( scene, camera );

	}

</script>
</body>
</html>